config/routes.rb
Rails.application.routes.draw do

  root 'creations#index'
  resources :users
  resources :creations
  resources :categories

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :creations
end

app/models/creation.rb
# == Schema Information
#
# Table name: creations
#
#  id          :integer          not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text
#  user_id     :integer
#  category_id :integer
#

class Creation < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :creations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    
  end

  def new
  end

  def edit
  end

  def show
    @creations = Creation.all
    @users = User.all
    @categories = Category.all
    @category = Category.find(params[:id])
  end
end

app/controllers/creations_controller.rb
class CreationsController < ApplicationController
  def index
    @creations = Creation.all
    @users = User.all
    @categories = Category.all
  end

  def new
    @creations = Creation.all
    @users = User.all
    @categories = Category.all
    @creation = Creation.new
    @category_names = Category.pluck(:name)
    @user_names = User.pluck(:name)
  end

  def create
    parameters = params[:creation]
    @category_id = Category.find_by(name: parameters["category_id"]).id
    @user_id = User.find_by(name: parameters["user_id"]).id
    @creation = Creation.new(creation_params)
    @creation.category_id = @category_id
    @creation.user_id = @user_id
    @creation.save
    redirect_to @creation
  end

  def edit
  end

  def show
    @creations = Creation.all
    @users = User.all
    @categories = Category.all
    @creation = Creation.find(params[:id])
  end

  def destroy
    Creation.find(params[:id]).destroy
    redirect_to root_url
  end

  private
    def creation_params
      params.require(:creation).permit(:name, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def home
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.find(user_params)
  end

  def edit
    # @user = 
  end

  def show
    @creations = Creation.all
    @users = User.all
    @categories = Category.all
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:name, :username, :email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/creations_helper.rb
module CreationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<div id="category">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-9">
        <h3>Category / <%= @category.name %></h3>
        <div class="row">

          <% @category.creations.each do |creation| %>
            <div class="col-sm-6 col-md-4 creation">
              <%= render partial: 'creations/creation_box', locals: { creation: creation } %>
            </div>
          <% end %>

        </div>
      </div>
      <div class="col-sm-3">
        <%= render partial: 'layouts/sidebar', locals: { creations: @creations, users: @users } %>
      </div>
    </div>
  </div>
</div>

app/views/creations/_creation_box.html.erb
<div id="creation_box"> 
 <div class="thumbnail">
    <%= image_tag("thumbnail.svg") %>
    <div class="caption">
      <h3><%= link_to creation.name, creation %></h3>
      <p><%= creation.description.split(".").first %></p>
      <p>
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
        <span class="badge">4</span>
        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
        <span class="badge">4</span>
        <span class="creator">By: <%= link_to creation.user.name, creation.user %></span>
      </p>
    </div>
  </div>
</div>

app/views/creations/edit.html.erb
<h1>Creations#edit</h1>
<p>Find me in app/views/creations/edit.html.erb</p>

app/views/creations/index.html.erb
<div id="creations">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-9">
        <div class="row">

          <% @creations.each do |creation| %>
            <div class="col-sm-6 col-md-4 creation">
              <%= render partial: 'creations/creation_box', locals: { creation: creation } %>
            </div>
          <% end %>

        </div>
      </div>
      <div class="col-sm-3">
        <%= render partial: 'layouts/sidebar', locals: { creations: @creations, users: @users } %>
      </div>
    </div>
  </div>
</div>

app/views/creations/new.html.erb
<div id="new_creation">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-9">
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2">
            <%= simple_form_for @creation do |f| %>
              <%= f.input :name %>
              <%= f.input :description %>
              <%= f.input :category_id, collection: @category_names %>
              <%= f.input :user_id, collection: @user_names %>
              <%= f.button :submit %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <%= render partial: 'layouts/sidebar', locals: { creations: @creations, users: @users } %>
      </div>

    </div>
  </div>
</div>

app/views/creations/show.html.erb
<div id="creation">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-9">
        <div class="row">
          <div class="col-md-5">
            <div class="row">
              <div class="thumbnail">
                <%= image_tag("thumbnail.svg") %>
              </div>
            </div>
            <div class="row more-images">
              <div class="col-md-4 image">
                <div class="thumbnail">
                  <%= image_tag("thumbnail.svg") %>
                </div>
              </div>
              <div class="col-md-4 image">
                <div class="thumbnail">
                  <%= image_tag("thumbnail.svg") %>
                </div>
              </div>
              <div class="col-md-4 image">
                <div class="thumbnail">
                  <%= image_tag("thumbnail.svg") %>
                </div>
              </div>
            </div>
            
            <div class="row buttons">
              <h4>Downloads</h4>
              <hr/>
              <div class="col-md-6 button">
                <button type="button" class="btn btn-primary">Schematic</button>
              </div>
              <div class="col-md-6 button">
                <button type="button" class="btn btn-primary">Board</button>
              </div>
            </div>
          </div>
          <div class="col-md-7 content">
            <h3 class="header">
              <%= link_to @creation.user.name, @creation.user %> / <%= @creation.name %>
              <span class="category"><%= link_to @creation.category.name, @creation.category %></span>
              <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-trash"), creation_path, method: :delete, data: { confirm: "Are you sure?" }, class: "delete-icon" %>
            </h3>
            <p class="credits">
              <span class="like">
                <%= link_to content_tag(:span, " 104", class: "glyphicon glyphicon-thumbs-up"), "#" %>
                <!-- <span class="badge">104</span> -->
              </span>
              <span class="comment">
                <%= link_to content_tag(:span, " 56", class: "glyphicon glyphicon-comment"), "#" %>
                <!-- <span class="badge">56</span> -->
              </span>
              <span class="download">
                <%= link_to content_tag(:span, " 13", class: "glyphicon glyphicon-download"), "#" %>
                <!-- <span class="badge">13</span> -->
              </span>
            </p>
            <p class="description"><%= @creation.description %></p>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <%= render partial: 'layouts/sidebar', locals: { creations: @creations, users: @users } %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid">
    <p class="text-muted">&copy; <a href="http://www.rajanjamu.com" target="_blank">Rajan Gupta</a> @ <a href="http://www.codeastra.com" target="_blank">CodeAstra</a></p>
  </div>
</footer>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58423774-3', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Fuse</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- <li>
          <a href="#">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            Create
          </a>
        </li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            Rajan Gupta
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to content_tag(:span, "", class: "glyphicon glyphicon-plus") + "Create", new_creation_path %></li>
            <li><%= link_to content_tag(:span, "", class: "glyphicon glyphicon-folder-open") + "Profile", new_creation_path %></li>
            <li><%= link_to content_tag(:span, "", class: "glyphicon glyphicon-cog") + "Settings", new_creation_path %></li>
            <li class="divider"></li>
            <li><%= link_to content_tag(:span, "", class: "glyphicon glyphicon-log-out") + "Logout", new_creation_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sidebar.html.erb
<aside>
  <div class="panel panel-default">
    <div class="panel-heading">Top Creations</div>
    <div class="panel-body">
      <div class="list-group">
        <% @creations.each do |creation| %>
          <%= link_to creation, class: "list-group-item" do %>
            <%= creation.name %>
            <%= content_tag(:span, "4", class: "badge") %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">Top Creators</div>
    <div class="panel-body">
      <div class="list-group">
        <% @users.each do |user| %>
          <%= link_to user, class: "list-group-item" do %>
            <%= user.name %>
            <%= content_tag(:span, "4", class: "badge") %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

    <div class="panel panel-default">
    <div class="panel-heading">Top Categories</div>
    <div class="panel-body">
      <div class="list-group">
        <% @categories.each do |category| %>
          <%= link_to category, class: "list-group-item" do %>
            <%= category.name %>
            <%= content_tag(:span, "4", class: "badge") %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fuse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400' rel='stylesheet' type='text/css'>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container-fluid">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= render 'layouts/google_analytics' %>

</body>
</html>

app/views/static_pages/home.html.erb
<div id="home">
  <div class="bg"></div>
  <div class="site-branding">
    <div class="site-title"><h1>fuse</h1></div>
    <div class="site-description"><h3>github for electronic enthusiasts</h3></div>
  </div>
</div>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="container">
  <h1>Rajan</h1>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div id="user">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-9">
        <div class="row">
          <div class="col-md-offset-1 col-md-3 user-info">
            <div class="thumbnail">
              <%= image_tag("thumbnail.svg") %>
            </div>
            <h1 class="name"><%= @user.name %></h1>
            <h4 class="username"><%= @user.username %></h4>

            <hr/>
            <div class="info">
              <p class="country">
                <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                India
              </p>
              <p class="email">
                <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                <%= @user.email %>
              </p>
              <p class="joined">
                <span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span>
                Joined <%= @user.created_at.in_time_zone('Chennai').strftime("%d %b %Y") %>
              </p>
            </div>
            <hr/>

            <div class="credits">
              <p class="row numbers">
                <span class="col-xs-4">104</span>
                <span class="col-xs-4">56</span>
                <span class="col-xs-4">23</span>
              </p>
              <p class="row icons">
                <span class="col-xs-4 glyphicon glyphicon-thumbs-up"></span>
                <span class="col-xs-4 glyphicon glyphicon-comment"></span>
                <span class="col-xs-4 glyphicon glyphicon-user"></span>
              </p>
            </div>

            <div class="follow">
              <button type="button" class="btn btn-primary">Follow</button>
            </div>
          </div>
          <div class="col-md-8">
            <% @user.creations.each do |creation| %>
              <div class="col-sm-12 col-md-6 creation">
                <%= render partial: 'creations/creation_box', locals: { creation: creation } %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <%= render partial: 'layouts/sidebar', locals: { creations: @creations, users: @users } %>
      </div>
    </div>
  </div>
</div>